export const staticData = [
  {
    docket_id: "a1b2c3d4-1234-5678-9abc-0123456789ab",
    docket_status: "opened",
    docket_name: "Docket 1",
    agency: {
      agency_id: 1,
      agency_name: "Agency 1",
      agency_reference_number: "REF001",
    },
    caseType: {
      case_type_id: 1,
      case_type_name: "Type 1",
    },
    date_requested_from: "2022-01-01",
    date_requested_to: "2022-01-10",
    date_received_from: "2022-01-05",
    date_received_to: "2022-01-15",
    hearingType: {
      hearing_type_id: 1,
      hearing_type: "Type A",
      hearing_date: "2024-03-05",
    },
    party: {
      party_id: 1,
      party_name: "Party A",
      party_type: "Type X",
    },
    staff_assigned: "Staff A",
    staff_id: 1,
    judge: "Judge A",
    judge_id: 1,
  },
  {
    docket_id: "b2c3d4e5-2345-6789-abcd-123456789abc",
    docket_status: "opened",
    docket_name: "Docket 2",
    agency: {
      agency_id: 1,
      agency_name: "Agency 1",
      agency_reference_number: "REF002",
    },
    caseType: {
      case_type_id: 2,
      case_type_name: "Type 2",
    },
    date_requested_from: "2022-01-02",
    date_requested_to: "2022-01-12",
    date_received_from: "2022-01-06",
    date_received_to: "2022-01-16",
    hearingType: {
      hearing_type_id: 2,
      hearing_type: "Type B",
      hearing_date: "2024-03-08",
    },
    party: {
      party_id: 2,
      party_name: "Party B",
      party_type: "Type Y",
    },
    staff_assigned: "Staff B",
    staff_id: 2,
    judge: "Judge B",
    judge_id: 2,
  },
  {
    docket_id: "c3d4e5f6-3456-789a-bcde-23456789abcd",
    docket_status: "opened",
    docket_name: "Docket 3",
    agency: {
      agency_id: 2,
      agency_name: "Agency 2",
      agency_reference_number: "REF003",
    },
    caseType: {
      case_type_id: 3,
      case_type_name: "Type 3",
    },
    date_requested_from: "2022-01-03",
    date_requested_to: "2022-01-13",
    date_received_from: "2022-01-07",
    date_received_to: "2022-01-17",
    hearingType: {
      hearing_type_id: 3,
      hearing_type: "Type C",
      hearing_date: "2024-03-03",
    },
    party: {
      party_id: 3,
      party_name: "Party C",
      party_type: "Type Z",
    },
    staff_assigned: "Staff C",
    staff_id: 3,
    judge: "Judge C",
    judge_id: 3,
  },
  {
    docket_id: "d4e5f6g7-4567-89ab-cdef-3456789abcde",
    docket_status: "closed",
    docket_name: "Docket 4",
    agency: {
      agency_id: 2,
      agency_name: "Agency 2",
      agency_reference_number: "REF004",
    },
    caseType: {
      case_type_id: 4,
      case_type_name: "Type 4",
    },
    date_requested_from: "2022-01-04",
    date_requested_to: "2022-01-14",
    date_received_from: "2022-01-08",
    date_received_to: "2022-01-18",
    hearingType: {
      hearing_type_id: 4,
      hearing_type: "Type D",
      hearing_date: "2024-03-07",
    },
    party: {
      party_id: 4,
      party_name: "Party D",
      party_type: "Type P",
    },
    staff_assigned: "Staff D",
    staff_id: 4,
    judge: "Judge D",
    judge_id: 4,
  },
  {
    docket_id: "e5f6g7h8-5678-9abc-def0-456789abcdef",
    docket_status: "opened",
    docket_name: "Docket 5",
    agency: {
      agency_id: 3,
      agency_name: "Agency 3",
      agency_reference_number: "REF005",
    },
    caseType: {
      case_type_id: 5,
      case_type_name: "Type 5",
    },
    date_requested_from: "2022-01-05",
    date_requested_to: "2022-01-15",
    date_received_from: "2022-01-09",
    date_received_to: "2022-01-19",
    hearingType: {
      hearing_type_id: 5,
      hearing_type: "Type E",
      hearing_date: "2024-03-09",
    },
    party: {
      party_id: 5,
      party_name: "Party E",
      party_type: "Type Q",
    },
    staff_assigned: "Staff E",
    staff_id: 5,
    judge: "Judge E",
    judge_id: 5,
  },
];
